name: Pixi-CRS CI Pipeline

on:
  # Trigger the workflow on push,
  # but only for the master branch
  push:
    branches:
      - github-actions

jobs:
  build:
    name: Start Pixi and the CRS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

#      - name: Debugging 
#        run: pwd
#      - name: Debugging 
#        run: ls

      - name: Starting Pixi and CRS with docker-compose up
        run: docker-compose -f docker-compose.yaml --env-file compose-gcp.env up -d

      - name: Run Testcafe Tests Pixi without and with CRS
        run: docker run --volume testcafe/tests_container_ip:/tests --rm testcafe/testcafe --skip-js-errors 'chromium:headless --no-sandbox'

