name: Pixi-CRS CI Pipeline

on:
  # Trigger the workflow on push,
  # but only for the master branch
  push:
    branches:
      - github-actions

jobs:
  build:
    name: Start Pixi and the CRS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Debugging 
        run: pwd
      - name: Debugging 
        run: ls

      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yaml --env-file compose-gcp.env up -d

